// physiocoach-ai-web/src/app/shared/ui/exercise-visual.component.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core';

import type { ExerciseImageMedia } from './exercise-image-resolver';
import {
  type ExerciseVisualResult,
  resolveExerciseVisual,
} from './exercise-visual-resolver';

@Component({
  selector: 'pc-exercise-visual',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './exercise-visual.component.html',
  host: {
    class: 'block min-w-0',
  },
})
export class ExerciseVisualComponent {
  readonly name = input('');
  readonly masterExerciseId = input<string | null | undefined>(null);
  readonly movementPattern = input<string | null | undefined>(null);
  readonly muscleGroup = input<string | null | undefined>(null);
  readonly media = input<ExerciseImageMedia | null | undefined>(null);
  readonly loading = input(false);
  readonly compact = input(false);

  protected readonly mediaFailed = signal(false);
  protected readonly stageClasses = computed(() =>
    this.compact()
      ? 'h-14 w-14 p-1 bg-white rounded-lg border border-slate-200'
      : 'w-full max-w-2xl mx-auto aspect-[4/3] sm:aspect-[3/2] lg:aspect-[16/9] p-2 sm:p-3 bg-white rounded-2xl border border-slate-200 shadow-sm flex items-center justify-center',
  );

  protected readonly visual = computed<ExerciseVisualResult>(() => {
    if (this.mediaFailed()) {
      return { kind: 'unavailable' };
    }
    const media = this.mediaFailed() ? null : this.media();
    return resolveExerciseVisual({
      name: this.name(),
      masterExerciseId: this.masterExerciseId(),
      movementPattern: this.movementPattern(),
      muscleGroup: this.muscleGroup(),
      media,
    });
  });

  protected readonly attribution = computed(() => {
    const visual = this.visual();
    if (visual.kind !== 'media') {
      return '';
    }

    const media = visual.media;
    const attributionText = media.attributionText?.trim();
    if (attributionText) {
      return attributionText;
    }

    const author = media.licenseAuthor?.trim();
    const source = media.source?.trim();
    const license = media.licenseName?.trim();
    if (author && source) {
      return `Source: ${source} / ${author}`;
    }
    if (source) {
      return `Source: ${source}`;
    }
    if (author && license) {
      return `${license} / ${author}`;
    }
    if (license) {
      return license;
    }
    return '';
  });

  protected onImageError(): void {
    console.warn('exercise_visual.image_failed', {
      masterExerciseId: this.masterExerciseId(),
      name: this.name(),
    });
    this.mediaFailed.set(true);
  }

  protected onImageLoad(): void {
    this.mediaFailed.set(false);
  }

}

<figure data-exercise-visual class="grid min-w-0 gap-2" [class.h-full]="compact()">
  <div
    class="relative grid min-w-0 place-items-center overflow-hidden rounded-xl bg-white p-2 shadow-xs border border-slate-200 dark:border-slate-700/80"
    [class]="stageClasses()"
  >
    @if (loading()) {
      <div data-exercise-visual-loading class="absolute inset-0 grid place-items-center bg-white" aria-label="Loading exercise visual">
        <span class="pc-skeleton h-full w-full rounded-none"></span>
      </div>
    }

    @let currentVisual = visual();
    @if (currentVisual.kind === 'media') {
      <img
        data-exercise-image
        class="h-full max-h-64 sm:max-h-72 w-full object-contain mx-auto"
        [src]="currentVisual.url"
        [alt]="name() ? 'Exercise image: ' + name() : 'Exercise image'"
        loading="lazy"
        referrerpolicy="no-referrer"
        (error)="onImageError()"
        (load)="onImageLoad()"
      />
    } @else {
      <div data-exercise-visual-unavailable class="hidden" aria-hidden="true"></div>
    }
  </div>

  @if (!compact() && attribution()) {
    <figcaption data-exercise-attribution class="text-[0.6875rem] text-muted">
      {{ attribution() }}
    </figcaption>
  }
</figure>

// physiocoach-ai-web/src/components/ui/ExerciseVisual.tsx
import { useState } from 'react';
import { Dumbbell } from 'lucide-react';
import {
  resolveExerciseVisual,
  type ExerciseImageMedia,
} from '../../services/exercise-visual-resolver';

export interface ExerciseVisualProps {
  name: string;
  masterExerciseId?: string | null;
  movementPattern?: string | null;
  muscleGroup?: string | null;
  media?: ExerciseImageMedia | null;
  compact?: boolean;
  className?: string;
  showAttribution?: boolean;
}

export function ExerciseVisual({
  name,
  masterExerciseId,
  movementPattern,
  muscleGroup,
  media,
  compact = false,
  className = '',
  showAttribution = false,
}: ExerciseVisualProps) {
  const [errorCount, setErrorCount] = useState(0);
  const [loaded, setLoaded] = useState(false);

  const visual = resolveExerciseVisual({
    name,
    masterExerciseId,
    movementPattern,
    muscleGroup,
    media,
  });

  const currentSrc =
    errorCount === 0 ? visual.url : visual.fallbackUrl || '/images/exercises/fallback.webp';

  const handleError = () => {
    setErrorCount((prev) => prev + 1);
  };

  const handleLoad = () => {
    setLoaded(true);
  };

  const attributionText = visual.media?.attributionText || visual.media?.source || '';

  if (compact) {
    return (
      <div
        className={`relative flex h-full w-full items-center justify-center overflow-hidden rounded-xl bg-white p-1 ${className}`}
      >
        <img
          src={currentSrc}
          alt={name}
          onError={handleError}
          onLoad={handleLoad}
          className={`h-full w-full object-contain transition-opacity duration-200 ${
            loaded ? 'opacity-100' : 'opacity-0'
          }`}
          loading="lazy"
        />
        {!loaded && (
          <div className="absolute inset-0 grid place-items-center bg-zinc-900">
            <Dumbbell className="h-5 w-5 text-zinc-600 animate-pulse" />
          </div>
        )}
      </div>
    );
  }

  return (
    <div
      className={`relative flex flex-col items-center justify-center overflow-hidden rounded-2xl border border-zinc-800 bg-white p-2 sm:p-3 ${className}`}
    >
      <div className="relative flex aspect-square sm:aspect-video w-full max-w-sm items-center justify-center overflow-hidden rounded-xl bg-white">
        {!loaded && (
          <div className="absolute inset-0 flex items-center justify-center bg-zinc-900">
            <span className="h-6 w-6 animate-spin rounded-full border-2 border-lime-400 border-r-transparent" />
          </div>
        )}
        <img
          src={currentSrc}
          alt={name}
          onError={handleError}
          onLoad={handleLoad}
          className={`h-full w-full object-contain p-2 transition-all duration-300 ${
            loaded ? 'scale-100 opacity-100' : 'scale-95 opacity-0'
          }`}
        />
      </div>

      {showAttribution && attributionText && (
        <div className="mt-2 flex items-center gap-1 text-[10px] text-zinc-500">
          <span>{attributionText}</span>
        </div>
      )}
    </div>
  );
}
